### ISSUE TITLE
Remove phpunit PHAR build from Git version control

### ISSUE THREAD

**Issue by peter279k** [liamdennehy/eidas-certificate-parse#19]
As title, the `phpunit` phar build is about the dependencies of required development.

I think we don't have to let this be in Git version control.

IMHO, the proper way is to remove this PHAR build and define correct `phpunit` version inside `require-dev` block on `composer.json`.

**Comment by liamdennehy** [comment]
@peter279k Did you mean to create this issue here? We were discussing this question in https://github.com/robrichards/xmlseclibs/pull/200

Perhaps you meant to create this in https://github.com/robrichards/xmlseclibs/issues?

**Comment by peter279k** [comment]
Ok. Moving the issue to there.
