### ISSUE TITLE
Missing composer dependency

### ISSUE THREAD

**Issue by Ludo444** [liamdennehy/eidas-certificate-parse#76]
Currently when trying to install, composer fails to resolve dependency.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for liamdennehy/eidas-certificate ^3.5 -> satisfiable by liamdennehy/eidas-certificate[3.5.0].
    - liamdennehy/eidas-certificate 3.5.0 requires robrichards/xmlseclibs dev-mgf1#c2e5a1424804c462ec5342bb68858725cbe78256@dev -> no matching package found.
```

Looks like that branch was merged and proprely released in `xmlseclibs` ?

**Comment by liamdennehy** [comment]
Apologies for this, haven't paid attention in a while. At the time [xmlseclibs](https://github.com/robrichards/xmlseclibs) didn't support RSA-PSS signatures which the German Trust List started using. Will look into this and see what the current state is.

**Comment by liamdennehy** [comment]
Thanks for the fix, and spotting useless dependency too! :+1:

**Comment by liamdennehy** [comment]
Thanks for the fix, and spotting useless dependency too! :+1: 

Will now work on seeing if Germany's TL can be verified against latest phpseclib

**Comment by Ludo444** [comment]
actually I noticed problem with Switzerland today, they are using sha384WithECDSA currently and lib was not able to process it

**Comment by liamdennehy** [comment]
I'm working on PR #80 to toggle signature verification, I'd rather process a TL without signature verification than exclude it, then leave verification up to the user. I don't see any plans on xmlseclib to handle these any time soon :disappointed:
